Repository iwatkot/maps4fs, pull requests merged in 2025-01, with the labels that each got.

#111 USGS 1m implementation
  maps4fs/generator/dtm.py
Labels: enhancement

#129 DTM refactor and new NRW DTM provider
  dev/requirements.txt
  docs/dtm_providers.md
  maps4fs/__init__.py
  maps4fs/generator/dtm/dtm.py
  maps4fs/generator/dtm/nrw.py
  maps4fs/generator/dtm/srtm.py
  maps4fs/generator/dtm/usgs.py
  requirements.txt
  webui/generator.py
Labels: enhancement, DTM Provider

#141 Refactoring Components I3D, Config
  .dockerignore
  .gitignore
  .pylintrc
  README.md
  demo.py
  dev/clean_trash.ps1
  dev/clean_trash.sh
  maps4fs/generator/background.py
  maps4fs/generator/component/__init__.py
  maps4fs/generator/component/base/__init__.py
  maps4fs/generator/component/base/component.py
  maps4fs/generator/component/base/component_xml.py
  maps4fs/generator/component/config.py
  maps4fs/generator/component/i3d.py
  maps4fs/generator/dem.py
  maps4fs/generator/game.py
  maps4fs/generator/grle.py
  maps4fs/generator/i3d.py
  maps4fs/generator/map.py
  maps4fs/generator/satellite.py
  maps4fs/generator/settings.py
  maps4fs/generator/texture.py
  maps4fs/toolbox/background.py
  webui/templates.py
Labels: Refactoring

#143 GRLE Component refactoring WIP
  .pylintrc
  README.md
  demo.py
  maps4fs/generator/component/base/component_image.py
  maps4fs/generator/component/base/component_xml.py
  maps4fs/generator/component/grle.py
  maps4fs/generator/dtm/dtm.py
  maps4fs/generator/game.py
  maps4fs/generator/settings.py
  maps4fs/generator/texture.py
  webui/templates.py
Labels: wip, Refactoring

#144 Component Background refactoring
  .pylintrc
  demo.py
  maps4fs/generator/component/background.py
  maps4fs/generator/component/base/component_image.py
  maps4fs/generator/component/base/component_mesh.py
  maps4fs/generator/game.py
  maps4fs/generator/map.py
  maps4fs/generator/satellite.py
  maps4fs/generator/settings.py
Labels: wip, Refactoring

#142 Scotland, Finland, Italy, Flanders, Spain, France and Norway DTM providers
  .pylintrc
  .vscode/launch.json
  docs/dtm_providers.md
  maps4fs/__init__.py
  maps4fs/generator/dtm/base/wcs.py
  maps4fs/generator/dtm/base/wms.py
  maps4fs/generator/dtm/dtm.py
  maps4fs/generator/dtm/finland.py
  maps4fs/generator/dtm/flanders.py
  maps4fs/generator/dtm/france.py
  maps4fs/generator/dtm/italy.py
  maps4fs/generator/dtm/niedersachsen.py
  maps4fs/generator/dtm/norway.py
  maps4fs/generator/dtm/scotland.py
  maps4fs/generator/dtm/spain.py
  maps4fs/generator/dtm/usgs.py
  maps4fs/toolbox/background.py
  webui/generator.py
Labels: DTM Provider

#148 DEM settings refactoring
  README.md
  docs/dem.md
  maps4fs/generator/component/background.py
  maps4fs/generator/dem.py
  maps4fs/generator/dtm/dtm.py
  maps4fs/generator/dtm/srtm.py
  maps4fs/generator/settings.py
  webui/templates.py
Labels: Refactoring

#151 Cutting out the center of the mesh
  Dockerfile
  README.md
  dev/requirements.txt
  docs/create_background_terrain.md
  maps4fs/generator/component/background.py
  maps4fs/generator/component/base/component_mesh.py
  maps4fs/generator/settings.py
  requirements.txt
  tests/test_generator.py
  webui/templates.py
Labels: enhancement

#152 Add coverage map and DTM provider table to main docs
  README.md
  docs/mapchart_coverage_map_definition.txt
Labels: documentation

#153 Denmark DTM provider
  maps4fs/__init__.py
  maps4fs/generator/dtm/denmark.py
Labels: DTM Provider

#156 Switzerland DTM provider
  README.md
  docs/mapchart_coverage_map_definition.txt
  maps4fs/__init__.py
  maps4fs/generator/dtm/switzerland.py
Labels: DTM Provider

#159 Version check update
  webui/config.py
Labels: enhancement

#165 ArcticDEM, REMA Antarctic, Czechia, Sachsen-Anhalt DTM providers
  README.md
  maps4fs/__init__.py
  maps4fs/generator/dtm/arctic.py
  maps4fs/generator/dtm/czech.py
  maps4fs/generator/dtm/rema.py
  maps4fs/generator/dtm/sachsenanhalt.py
Labels: DTM Provider

#164 Switch USGS to WCS
  maps4fs/__init__.py
  maps4fs/generator/dtm/usgs.py
  maps4fs/generator/dtm/usgs_wcs.py
Labels: DTM Provider

#167 Some initial error handling for DEM/DTM
  maps4fs/generator/dem.py
  maps4fs/generator/dtm/arctic.py
  maps4fs/generator/dtm/baden.py
  maps4fs/generator/dtm/bavaria.py
  maps4fs/generator/dtm/canada.py
  maps4fs/generator/dtm/czech.py
  maps4fs/generator/dtm/denmark.py
  maps4fs/generator/dtm/dtm.py
  maps4fs/generator/dtm/england.py
  maps4fs/generator/dtm/finland.py
  maps4fs/generator/dtm/flanders.py
  maps4fs/generator/dtm/france.py
  maps4fs/generator/dtm/hessen.py
  maps4fs/generator/dtm/italy.py
  maps4fs/generator/dtm/mv.py
  maps4fs/generator/dtm/niedersachsen.py
  maps4fs/generator/dtm/norway.py
  maps4fs/generator/dtm/nrw.py
  maps4fs/generator/dtm/rema.py
  maps4fs/generator/dtm/sachsenanhalt.py
  maps4fs/generator/dtm/scotland.py
  maps4fs/generator/dtm/spain.py
  maps4fs/generator/dtm/switzerland.py
  maps4fs/generator/dtm/usgs_wcs.py
Labels: Refactoring

#170 Lithuania DTM provider
  README.md
  maps4fs/__init__.py
  maps4fs/generator/dtm/__init__.py
  maps4fs/generator/dtm/lithuania.py
Labels: DTM Provider
